name: Scheduled dbt Build

on:
  schedule:
    - cron: "0 5 * * 1-5" # Tous les jours de la semaine à 5h00 UTC
  workflow_dispatch:

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "${{ secrets.DBT_ACCOUNT }}"
      user: "${{ secrets.DBT_USER }}"
      password: "${{ secrets.DBT_PASSWORD }}"
      role: "${{ secrets.DBT_ROLE }}"
      database: "${{ secrets.DBT_DATABASE }}"
      warehouse: "${{ secrets.DBT_WAREHOUSE }}"
      schema: "${{ secrets.DBT_SCHEMA }}"
EOL:
  - name: Run dbt build
    run: dbt build
