name: hello_world_on_push

on:
  push:
    branches:
      - "**"

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        run: echo "Hello, world!"
